### ISSUE TITLE
SampleRNN performance

### ISSUE THREAD

**Issue by abhilashi** [soroushmehr/sampleRNN_ICLR2017#7]
On a Tesla K80, how much time does an epoch take? For the samples listed on soundcloud, how many epochs is it? What hardware is used?

**Comment by soroushmehr** [comment]
For music dataset with a K80 it took us ~20 epochs in three days. You will get so-so samples much sooner. As long as the rest of the machine is decent enough (which I assume that's the case as you have a K80 installed) the rest should be fine.

**Comment by abhilashi** [comment]
@soroushmehr thanks much for the quick reply :) Is this on two or three tier?

**Comment by soroushmehr** [comment]
It's for both, give or take a few.

**Comment by kylemcdonald** [comment]
@soroushmehr i'm getting very different performance (much slower) for the music dataset. if you have a moment i would appreciate any advice.

i'm running a k80 on google compute engine. 8 CPUs, 30 GB of RAM. the image is on a 10GB disk and i have a 250GB SSD attached for storage. here's an excerpt from the training:

```
Wall clock time spent before training started: 0.11h                                                                                                                                                        
Training!
0 500 1000
Validation! Done!

>>> Best validation cost of 1.7006663084 reached. Testing! Done!
>>> test cost:1.70596313477     total time:390.858022928
epoch:0 total iters:1460        wall clock time:1.82h
>>> Lowest valid cost:1.7006663084       Corresponding test cost:1.70596313477
        train cost:1.8725       total time:1.50h        per iter:3.699s
        valid cost:1.7007       total time:0.11h
        test  cost:1.7060       total time:0.11h
Saving params! Done!
Train info saved! And plotted!
Sampling! 20 samples of 5 seconds length generated in 1773.51222897 seconds. Done!
Validation Done!
Back to Training...
1500 2000 2500
Validation! Done!

>>> Best validation cost of 1.6106518507 reached. Testing! Done!
>>> test cost:1.60985767841     total time:390.360123158
epoch:0 total iters:2916        wall clock time:4.03h
>>> Lowest valid cost:1.6106518507       Corresponding test cost:1.60985767841
        train cost:1.6607       total time:3.00h        per iter:3.704s
        valid cost:1.6107       total time:0.11h
        test  cost:1.6099       total time:0.11h
Saving params! Done!
Train info saved! And plotted!
Sampling! 20 samples of 5 seconds length generated in 1770.73614192 seconds. Done!
Validation Done!
Back to Training...
3000 3500 4000
Validation! Done!

>>> Best validation cost of 1.54390776157 reached. Testing! Done!
>>> test cost:1.54205977917     total time:389.498682976
epoch:0 total iters:4378        wall clock time:6.25h
>>> Lowest valid cost:1.54390776157      Corresponding test cost:1.54205977917
        train cost:1.5383       total time:4.50h        per iter:3.701s
        valid cost:1.5439       total time:0.11h
        test  cost:1.5421       total time:0.11h
Saving params! Done!
Train info saved! And plotted!
Sampling! 20 samples of 5 seconds length generated in 1747.0210681 seconds. Done!
Validation Done!
Back to Training...
4500 5000 5500
Validation! Done!
epoch:0 total iters:5842        wall clock time:8.34h
>>> Lowest valid cost:1.54390776157      Corresponding test cost:1.54205977917
        train cost:1.5426       total time:6.00h        per iter:3.698s
        valid cost:1.5653       total time:0.11h
        test  cost:1.5421       total time:0.00h
Saving params! Done!
Train info saved! And plotted!
Sampling! 20 samples of 5 seconds length generated in 1747.70665789 seconds. Done!
Validation Done!
Back to Training...
6000 6500 7000 [Another epoch]
Validation! Done!

>>> Best validation cost of 1.50889408588 reached. Testing! Done!
>>> test cost:1.50275349617     total time:389.24376297
epoch:1 total iters:7251        wall clock time:10.49h
>>> Lowest valid cost:1.50889408588      Corresponding test cost:1.50275349617
        train cost:1.4716       total time:7.44h        per iter:3.695s
        valid cost:1.5089       total time:0.11h
        test  cost:1.5028       total time:0.11h
Saving params! Done!
Train info saved! And plotted!
Sampling! 20 samples of 5 seconds length generated in 1744.28628492 seconds. Done!
Validation Done!
Back to Training...

Validation! Done!

>>> Best validation cost of 1.4724830389 reached. Testing! Done!
>>> test cost:1.46564877033     total time:389.432633162
epoch:1 total iters:7308        wall clock time:11.25h
>>> Lowest valid cost:1.4724830389       Corresponding test cost:1.46564877033
        train cost:1.4710       total time:7.50h        per iter:3.695s
        valid cost:1.4725       total time:0.11h
        test  cost:1.4656       total time:0.11h
Saving params! Done!
Train info saved! And plotted!
Sampling! 20 samples of 5 seconds length generated in 1741.3295691 seconds. Done!
Validation Done!
Back to Training...
7500 8000 8500
Validation! Done!

>>> Best validation cost of 1.42520678043 reached. Testing! Done!
>>> test cost:1.4195625782      total time:390.478302002
epoch:1 total iters:8770        wall clock time:13.45h
>>> Lowest valid cost:1.42520678043      Corresponding test cost:1.4195625782
        train cost:1.3996       total time:9.00h        per iter:3.695s
        valid cost:1.4252       total time:0.11h
        test  cost:1.4196       total time:0.11h
Saving params! Done!
Train info saved! And plotted!
Sampling! 20 samples of 5 seconds length generated in 1760.72217083 seconds. Done!
Validation Done!
Back to Training...
9000 9500
```

It looks like it's generally working:

![train_log](https://cloud.githubusercontent.com/assets/157106/24333417/8b4a83e0-120c-11e7-9394-2fbc0bbabbbe.png)

if i run `watch -n0.1 nvidia-smi` i can see it fluttering between ~900MB of memory usage and ~3200MB (out of 12GB total).

running `htop` i can see python is using one core at 100%:

```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
 1614 kyle       20   0 55.3G 2117M  186M R 99.5  7.0 15h04:02 python ...
```

the memory use clearly isn't a bottleneck (7%) but it seems like the CPU use is very high. i thought training was usually a GPU constrained process?

- K80 Driver Version: 375.26
- CUDA 8.0.61_375.26
- cuDNN v5.1
- lasagne 0.2.dev1
- python 2.7.6
- latest numpy and theano installed with conda

the main differences are the python version, and possibly the numpy version.. but if it's generally working, i wouldn't expect a big problem from these.

i did notice the "switch to gpuarray" warning when running the command in the readme, but the fact that the gpu is being put to use makes me think the code doesn't have to be converted yet.

**Comment by kundan2510** [comment]
It looks like you did not specify THEANO_FLAGS=mode=FAST_RUN,device=gpu0,floatX=float32 to tell theano to use GPU.
That may be causing the model to run on cpu and hence the slowdown.

Is it the case?

**Comment by kylemcdonald** [comment]
hi @kundan2510 i copied the command from the readme, which includes `THEANO_FLAGS=mode=FAST_RUN,device=gpu0,floatX=float32`. also, would i see 3GB of GPU memory being used by python in `nvidia-smi` if theano was not using the GPU? is there another way to know that theano is not using the GPU?

i didn't paste the beginning of the output, but i remember it mentioning that the GPU was being used.

i did find one mistake, however, which is that i am using CUDA but not cuDNN. is this speed more like CPU-only speed, CUDA-only speed, or is it possible that everything is correct and there is another bottleneck like between the RAM and GPU, or due to this being run in a VM?

**Comment by kundan2510** [comment]
This seems like CPU-only speed to me. We are anyway not using any cuDNN functions, hence, I would not expect any speedup-drop due to absence of cuDNN.
Following command should let you see if you are able to use GPU or not:
`THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python -c "import theano"`
If it uses GPU, it will show that you are using GPU k80. Also, when you run the code, the first line printed should be "Using gpu device 0: Tesla K80 ...." which is missing in the output you copied in one of the previous comment.

**Comment by kylemcdonald** [comment]
set this up again on a local machine with a gtx 980, similar results:

```
$ THEANO_FLAGS=mode=FAST_RUN,device=gpu0,floatX=float32 python -c "import theano"
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 980 (CNMeM is disabled, cuDNN 5110)
```

and here's the beginning of the command running:

```
Experiment started at: 2017-03-26 19:41
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 980 (CNMeM is disabled, cuDNN 5110)
Created experiment tag for these args:
models-three_tier-three_tier.py-expBEST_3TIER-seq_len512-big_frame_size8-frame_size2-emb_size256-skip_connF-dim1024-n_rnn1-rnn_typeGRU-q_levels256-q_typelinear-batch_size128-weight_normT-learn_h0T-which_setMUSIC-lr0.001
Python:
	sys.version_info	sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
Numpy:
	.__version__	1.12.0
Theano:
	.__version__	0.9.0.dev-b3d19ce8e8d7cdf87c3f84599be81647803aa1f6


All passed args:
['models/three_tier/three_tier.py', '--exp', 'BEST_3TIER', '--seq_len', '512', '--big_frame_size', '8', '--frame_size', '2', '--emb_size', '256', '--skip_conn', 'False', '--dim', '1024', '--n_rnn', '1', '--rnn_type', 'GRU', '--q_levels', '256', '--q_type', 'linear', '--batch_size', '128', '--weight_norm', 'True', '--learn_h0', 'True', '--which_set', 'MUSIC']

...
```

it looks like it's using the GPU but still taking longer than the 20 epochs in 72 hours.

i'll run this for a while and check the timing.

**Comment by kundan2510** [comment]
Here is a result for some user who trained 9 epochs in 24hrs on gtx1080. https://github.com/soroushmehr/sampleRNN_ICLR2017/issues/9 You may want to try the same config.

**Comment by kylemcdonald** [comment]
thanks @kundan2510. i tried the same config as #9 on the gtx 980, and it ran out of memory (`Error allocating 1073741824 bytes of device memory (out of memory). Driver report 464125952 bytes free and 4232183808 bytes total`). then i tried it on the K80 and it doesn't run out of memory, but still seems to go just as slowly as before.

here are my complete version numbers:

K80 (Google Compute Engine):
- NVIDIA-SMI 375.26, Driver Version: 375.26
- Cuda compilation tools, release 8.0, V8.0.61
- cuDNN 5110
- Python 2.7.13
- numpy 1.12.1
- scipy 0.19.1
- theano 0.9.0.dev-b3d19ce8e8d7cdf87c3f84599be81647803aa1f6
- lasagne 0.2dev1

GTX 980
- NVIDIA-SMI 375.39, Driver Version: 375.39
- Cuda compilation tools, release 8.0, V8.0.61
- cuDNN 5110
- Python 2.7.12
- numpy 1.12.0
- scipy 0.18.1
- theano 0.9.0.dev-c697eeab84e5b8a74908da654b66ec9eca4f1291
- lasagne 0.2dev1

since you said that cuDNN is not being used, then i suspect 5110 vs 5105 should not make a difference. i also suspect that Python 2.7.13 vs 2.7.12 shouldn't make a difference. this leaves the possibilities of:

- theano
- CUDA/nvcc

maybe the thing that i'm missing is that theano 0.9 should *only* be used for the wavenet re-implementation, but not for the samplernn models? i will try to downgrade theano and test.

edit: still slow with theano 0.8.2 :/

i also tried enabling cnmem, which i noticed was disabled (and not explicitly enabled by the example command line flags). it helped a bit (from 5.2s to 4.3s on 980 and from 3.7s to 3.3s on K80) but not a big enough change to make a real difference.

for comparison i see 1.04s per iteration on GTX 1080 here https://github.com/soroushmehr/sampleRNN_ICLR2017/issues/8#issuecomment-289225752

and i think 20 epochs in 3 days comes out to around 1.7s per iteration.

so i'm basically trying to get from 3.3s down to 1-2s. seems like there's something still missing in terms of that last 30% performance.

edit again: with some more flags i seem to have gotten it down to 2.5s per iteration on the K80:

```
 THEANO_FLAGS=mode=FAST_RUN,device=gpu0,floatX=float32,optimizer_including=cudnn,lib.cnmem=1,nvcc.fastmath=True \
>         python -u models/two_tier/two_tier.py \
>         --exp BEST_2TIER \
>         --n_frames 64 \
>         --frame_size 16 \
>         --emb_size 256 \
>         --skip_conn False \
>         --dim 1024 --n_rnn 3 \
>         --rnn_type GRU \
>         --q_levels 256 \
>         --q_type linear \
>         --batch_size 64 \
>         --weight_norm True \
>         --learn_h0 True \
>         --which_set MUSIC
```

**Comment by soroushmehr** [comment]
You can have a look at `th_conf.txt` under that specific experiment. All the flags passed to Theano will be there. Look for suspicious flags in http://deeplearning.net/software/theano/tutorial/using_gpu.html and http://deeplearning.net/software/theano/library/config.html.

Another option would be to profile it (e.g. with `profile=True,profile_memory=True`) to see where the bottleneck is. This might give us more insight into what's happening during compilation and run.

Have you tried clearing the cache before launching the experiment? Whenever you change the Theano version, compiler, etc. or in general once in awhile, it is a good practice to clear it.

**Comment by kylemcdonald** [comment]
i'm put the entire directory online (temporarily). here's a link to [th_conf.txt](http://35.185.202.169/results_2t/models-two_tier-two_tier.py-expBEST_2TIER-n_frames64-frame_size16-emb_size256-skip_connF-dim1024-n_rnn3-rnn_typeGRU-q_levels256-q_typelinear-batch_size64-weight_normT-learn_h0T-which_setMUSIC-lr0.001/th_conf.txt)

i generally clear the theano cache often. in this case, i installed all the software fresh on the google compute instance, so there was no need to clear the cache in terms of version changes (though clearing out old experiments that might have hung was still relevant).

i looked through the flags and didn't see anything suspicious. i suspect that 2.5s vs 1.7s per iteration is just due to the hardware differences...?

**Comment by soroushmehr** [comment]
I didn't see anything abnormal. Although I don't have much experience with Google compute instance, maybe we are left to assume, as you said, there is a difference due to hardware and/or config.
